version: '3.7'
services:
  rest: 
    build: 
      context: ./src/api_endpoint/docker
      dockerfile: Dockerfile
    ports:
      - 80:8000
    volumes:
      - ./src/api_endpoint:/api_endpoint 
    entrypoint: ["/bin/bash" , "-c" , "docker/startup.sh"]
    
  redis:
    image: redis

  searcher: 
    build: 
      context: ./src/search/docker
      dockerfile: Dockerfile

    volumes:
      - ./src/search:/search
      - ./data/embeddings:/search/embeddings
      - ./data/permalinks:/search/permalinks

    entrypoint: ["/bin/bash" , "-c" , "python3 searcher.py"]

  data-processing:
    build: 
      context: ./src/data_processing/docker
      dockerfile: Dockerfile
    volumes:
      - ./src/data_processing:/job
      - ./data:/job/data
    
    entrypoint: ["/bin/bash" , "-c" ,  "spark-submit --executor-memory 4G --driver-memory 4G --executor-cores 4 ./filter.py"]

  


    



    
    

