version: '3.7'
services:
  rest: 
    build: 
      context: ./src/api_endpoint/docker
      dockerfile: Dockerfile
    ports:
      - 80:8000
    volumes:
      - ./src/api_endpoint:/api_endpoint 

    command: ["tail", "-f", "/dev/null"]
    
  redis:
    image: redis

  data-processing : 
    build:
      context: ./src/data_processing/docker
      dockerfile: Dockerfile
    
    volumes:
      - ./src/data_processing/:/job
      - ./data:/job/data

    command: ["tail", "-f", "/dev/null"]



    
    

