apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-endpoint
  labels:
    app: api-endpoint
spec:
  selector:
    matchLabels:
      app: api-endpoint
  template:
    metadata:
      labels:
        app: api-endpoint
    spec:
      # nodeName: alpha
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - alpha
      restartPolicy: Always
      containers:
      - name: api-endpoint
        image: fortytw0/api_endpoint:latest
        ports:
        - containerPort: 8000
        command: ["sleep"]
        args : ["infinity"]
        volumeMounts:
          - mountPath: /api_endpoint
            name: api-endpoint-vol
        env:
        - name: ALLOWED_HOSTS
          value: "198.59.83.28"
        - name: DEBUG
          value: "1"
          
      volumes:
        - name: api-endpoint-vol
          persistentVolumeClaim:
            claimName: api-endpoint-pvc
