apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-endpoint
  labels:
    app: api-endpoint
spec:
  selector:
    matchLabels:
      app: api-endpoint
  template:
    metadata:
      labels:
        app: api-endpoint
    spec:
      restartPolicy: Always
      containers:
      - name: api-endpoint
        image: fortytw0/api_endpoint:latest
        ports:
        - containerPort: 8000
        command: ["/bin/bash" , "-c"]
        args : ["python3 /api_endpoint/manage.py runserver 0.0.0.0:8000"]
        volumeMounts:
          - mountPath: /api_endpoint
            name: api-endpoint-vol
        env:
        - name: ALLOWED_HOSTS
          value: "172.26.147.249"
        - name: DEBUG
          value: "1"
          
      volumes:
        - name: api-endpoint-vol
          persistentVolumeClaim:
            claimName: api-endpoint-pv
