kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: api-endpoint-pvc
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi