kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: api-endpoint-pvc
  finalizers:
    - "null"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi