kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: api-endpoint-pvc
spec:
  volumeMode: Filesystem
  claimRef:
     namespace: default
     name: api-endpoint-pvc
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 9Gi