apiVersion: v1
kind: Service
metadata:
  name: api-endpoint-service
spec:
  selector:
    app: api-endpoint
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30008
  
